django_Notice_board/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

django_Notice_board/mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'
# 네임스페이스 중복을 막기위해 네임스페이스 추가

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    #<int:question_id>위치에 Question 리스트 인덱스 매핑
    # path 함수에 있는 URL 매핑에 name 속성을 부여하여 하드코딩 문제 해결
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

django_Notice_board/mysite/pybo/models.py
from django.db import models

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()


    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.question

django_Notice_board/mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question # 사용할 모델
        fields = ['subject', 'content']
        # QuestionForm에서 사용할 Question 모델의 속성
        # QuestionForm(forms.ModelForm):
        # Question Form은 forms.ModelForm을 상속했다.
        # 장고의 폼은 일반폼(forms.Form)과 모델 폼(forms.ModelForm)이 있는데.
        # 모델 폼은 Model과 연결된 폼으로 폼을 저장하면 연결된 모델의 데이터를
        # 저장할 수 있는 폼이다.
        # 모델 폼은 이너 클래스인 Meta 클래스가 반드시 필요하다.
        # Meta 클래스에는 사용할 모델과 모델의 속성을 적어야 한다.

        labels = {
            'subject':'제목',
            'content':'내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content':'답변내용',
        }

django_Notice_board/mysite/pybo/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseNotAllowed
from .models import Question
from django.utils import timezone
from .forms import QuestionForm, AnswerForm

def index(request):
    """
    pybo 목록 출력
    """
    question_list = Question.objects.order_by('-create_date')
    #order_by함수는 조회한 데이터를 특정 속성으로 정렬하며, -create_date는 작성일시의 역순을 의미한다.
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)
    # render함수는 context에 있는 Question 모델 데이터 question_list를

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question':question}
    return render(request, 'pybo/question_detail.html',context)

def answer_create(request, question_id):
    """
    pybo 답변 등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id = question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible')
    context = {'question': question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)
    # redirect 함수는 함수에 전달된 값을 참고하여 페이지 이동을 수행한다.


def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid(): # 유효성 검사
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

def index(request):
    page = request.GET.get('page', '1') # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10) # 페이지당 10개씩
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)

django_Notice_board/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="with=device-width,
     initial-scale=1, shrink-to-fit=no">
    <!--Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css'%}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css'%}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 네비게이션바 원활한 유지보수를 위해 분리 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 시작 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

django_Notice_board/mysite/templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

django_Notice_board/mysite/templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<!-- style sheet 로드를 위해 static 폴더 로드 -->
<div class="container my-3">
  <h2 class="border-bottom py-2">{{question.subject}}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">
        {{question.content}}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">
          {{question.create_date}}
        </div>
      </div>
    </div>
  </div>
    <h5 class="border-bottom my-3 py-2">
      {{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">
          {{ answer.content }}
        </div>
        <div class="d-flex justify-content-end">
          <div class="badge badge-light p-2">
            {{ answer.create_date }}
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
    <form action="{% url 'pybo:answer_create' question.id %}"
          method="post" class="my-3">
      {% csrf_token %}
      {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
        {% if field.error %}
        <div>
          <strong>{{ filed.label }}</strong>
          {{ filed.errors }}
        </div>
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}
      <div class="form-group">
        <textarea name="content" id="content"
                  class="form-control" rows="10"></textarea>
      </div>
      <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

django_Notice_board/mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post">
    <!-- action="{% url 'pybo:question_create' %}" -->
    <!-- 원래는 상단처럼 form에 action속성을 활용하여 urls와 매칭을 해주지만 -->
    <!-- 매칭을 선언해줄 경우 고정적으로 해당 값만 사용하게된다. -->
    <!-- 속성을 비워두면 현재 페이지의 URL이 DEFAULT ACTION으로 설정된다. -->
    <!-- 이를 활용하여 질문 등록 뿐만 아닌 질문 수정에도 활용 할 방안이 생긴다. -->
    {% csrf_token %}
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
      {% if field.errors %}
      <div>
        <strong>{{field.label}}</strong>
        {{field.errors}}
      </div>
      {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <div class="mb-3">
      <label for="subject" class="form-label">제목</label>
      <input type="text" class="form-control" name="subject" id="subject"
             value="{{form.subject.value|default_if_none:''}}">
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea class="form-control" name="content"
                id="content" rows="10">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <!-- form:question_create 함수에서 전달한 QuestionForm 객체 -->
    <!-- as_p:폼에 정의한 subject, content 속성에 해당하는 html코드를 자동으로 생성-->
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

django_Notice_board/mysite/templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 시작, 리스트를 다 그리고 시작한다 -->
    <ul class="pagination justify-content-center">
        <!--이전페이지-->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{question_list.previous_page_number}}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page_link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
    {% endif %}
    <!-- 페이지리스트 -->
    {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        <!-- |add:-5, |add:5 = 템플릿 필터, 현재 페이지 기준으로 좌우 5개씩 보이게한다. -->
        {% if page_number == question_list.number %}
    <li class="page-item active" aria-current="page">
        <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="?page={{page_number}}">{{page_number}}</a>
    </li>
    {% endif %}
        {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if question_list.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number}}">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
    </li>
    {% endif %}
    </ul>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}